name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # if one fails, do not cancel the other
      matrix:
        gambit-version: ['v4.9.3', 'master']
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get -y install openssl libssl-dev sqlite3 libsqlite3-dev
      - name: Cache gambit
        id: cache-gambit
        uses: actions/cache@v2
        with:
          path: gambit
          key: ${{ runner.os }}-gambit-${{ matrix.gambit-version }}
      - uses: actions/checkout@v2
        with:
          repository: 'gambit/gambit'
          ref: ${{ matrix.gambit-version }}
          path: 'gambit'
        if: steps.cache-gambit.outputs.cache-hit != 'true'
      - name: Build Gambit
        if: steps.cache-gambit.outputs.cache-hit != 'true'
        run: |
          cd gambit
          ./configure --prefix=$HOME/gambit --enable-single-host
          make
      - name: Install Gambit
        run: |
          cd gambit
          make install
          sudo ln -sf $HOME/gambit/bin/gsi /bin/gsi
          sudo ln -sf $HOME/gambit/bin/gsi-script /bin/gsi-script
          sudo ln -sf $HOME/gambit/bin/gsc /bin/gsc
      - name: Setup Gerbil build
        run: echo "(define (gerbil-version-string) \"git-$(git rev-parse --short=8 HEAD)\")" > src/gerbil/runtime/gx-version.scm
      - name: Build Gerbil gxi
        run: ./src/build.sh gxi
      - name: Build Gerbil stage0
        run: ./src/build.sh stage0
      - name: Build Gerbil stage1 final
        run: ./src/build.sh stage1 final
      - name: Build Gerbil stdlib
        run: ./src/build.sh stdlib
      - name: Build Gerbil lang
        run: ./src/build.sh lang
      - name: Build Gerbil tools
        run: ./src/build.sh tools
      - name: Run Gerbil tests
        run: |
          export GERBIL_HOME=${GITHUB_WORKSPACE}
          export PATH=${GITHUB_WORKSPACE}/bin:$PATH
          ./src/std/run-tests.ss
