name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get -y install openssl libssl-dev sqlite3 libsqlite3-dev
      - name: Cache gambit
        uses: actions/cache@v2
        env:
          cache-name: gambit
        with:
          path: $HOME/gambit
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('$HOME/gambit/bin/gsi') }}
      - name: Install Gambit
        run: bash .github/scripts/install-gambit.sh
      - name: Build
        run: |
          echo "(define (gerbil-version-string) \"git-$(git rev-parse --short=8 HEAD)\")" > src/gerbil/runtime/gx-version.scm
          export GERBIL_HOME=${GITHUB_WORKSPACE}
          cd src
          ./build.sh gxi
          ./build.sh stage0
          ./build.sh stage1 final
          ./build.sh stdlib
          ./build.sh lang
          ./build.sh tools
          export PATH=${GITHUB_WORKSPACE}/bin:$PATH
      - name: Run tests
        run: ./std/run-tests.ss
