name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get -y install openssl libssl-dev sqlite3 libsqlite3-dev
      - name: Cache gambit
        uses: actions/cache@v2
        env:
          cache-name: gambit
        with:
          path: $HOME/gambit
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('$HOME/gambit/bin/gsi') }}
      - name: Install Gambit
        run: bash .github/scripts/install-gambit.sh
      - name: Setup build
        run: |
          echo "(define (gerbil-version-string) \"git-$(git rev-parse --short=8 HEAD)\")" > src/gerbil/runtime/gx-version.scm
          export GERBIL_HOME=${GITHUB_WORKSPACE}
      - name: Build gxi
        run: ./src/build.sh gxi
      - name: Build stage0
        run: ./src/build.sh stage0
      - name: Build stage1 final
        run: ./src/build.sh stage1 final
      - name: Build stdlib
        run: ./src/build.sh stdlib
      - name: Build lang
        run: ./src/build.sh lang
      - name: Build tools
        run: ./src/build.sh tools
      - name: Setup PATH
        run: export PATH=${GITHUB_WORKSPACE}/bin:$PATH
      - name: Run tests
        run: ./src/std/run-tests.ss
